/***************************************************************************
 * @file     csu39fx10_syscfg.h
 * @version  V1.0.0
 * @author   0531
 * @date     2020-09-23 PM
 * @brief    该文件包含了...
 * 
 * @copyright Copyright (C) 2020 Chipsea Technologies Corp. All rights reserved.
 ****************************************************************************
 * @par 头文件
 *       csu39fx10.h \n
 *       cs_common.h
 * @attention
 *  硬件平台:	\n
 *  SDK版本：	.0.0
 * 
 * @par 修改日志:
 * <table>
 * <tr><th>Date        <th>Version  <th>Author    <th>Description
 * <tr><td>2018/08/17  <td>1.0      <td>0531	  <td>创建初始版本
 * </table>
 *
 *****************************************************************************/

#ifndef __CSU39FX10_SYSCFG_H__
#define __CSU39FX10_SYSCFG_H__

// Include external header file.
#include "csu39fx10.h"
#include "cs_common.h"


#ifdef __cplusplus
extern "C" {
#endif


/**
 * @addtogroup csu39fx10_sdk_chip	csu39fx10_sdk_chip
 * @{
 */

/**
 * @addtogroup csu39fx10_sdk_chip_fwlib	fwlib 
 * @{
 */

/**
 * @addtogroup csu39fx10_sdk_chip_fwlib_syscfg	syscfg
 * @{
 */

/** 
 * @addtogroup	syscfg_reg_cfgr1	reg: CFGR1 
 * @{
 */
//CFGR1
//VTHSEL
#define SYSCFG_VTHSEL_REG									CFGR1
#define SYSCFG_VTHSEL_POS									(7)
#define SYSCFG_VTHSEL_BITS									C_REG_BITS1
#define SYSCFG_VTHSEL_RESET									(0x00<< SYSCFG_VTHSEL_POS)
#define SYSCFG_VTHSEL_SET									(0x01<< SYSCFG_VTHSEL_POS)
#define SYSCFG_VTHSEL_MASK									(SYSCFG_VTHSEL_BITS<< SYSCFG_VTHSEL_POS)
#define __SYSCFG_VTHSEL_GET()								M_REG_GET(SYSCFG_VTHSEL_REG, SYSCFG_VTHSEL_POS, SYSCFG_VTHSEL_BITS)
#define __SYSCFG_VTHSEL_SET(SET)							M_REG_SET(SYSCFG_VTHSEL_REG, SYSCFG_VTHSEL_POS, SYSCFG_VTHSEL_BITS, SET)
#define __SYSCFG_VTHSEL_GET_SHIFT()							M_REG_GET_SHIFT(SYSCFG_VTHSEL_REG, SYSCFG_VTHSEL_POS, SYSCFG_VTHSEL_BITS)
#define __SYSCFG_VTHSEL_SET_SHIFT(POS_SET)					M_REG_SET_SHIFT(SYSCFG_VTHSEL_REG, SYSCFG_VTHSEL_POS, SYSCFG_VTHSEL_BITS, POS_SET)

//DIG_METCH[3:2]
//RESERVED

//DIG_METCH[1:0]
#define SYSCFG_DIG_METCH_REG								CFGR1
#define SYSCFG_DIG_METCH_POS								(3)
#define SYSCFG_DIG_METCH_BITS								C_REG_BITS2
#define SYSCFG_DIG_METCH_CC2A_DIS							(0x00<< SYSCFG_DIG_METCH_POS)
#define SYSCFG_DIG_METCH_CC2A_EN							(0x01<< SYSCFG_DIG_METCH_POS)
#define SYSCFG_DIG_METCH_CC1A_DIS               			(0x00<< SYSCFG_DIG_METCH_POS)
#define SYSCFG_DIG_METCH_CC1A_EN                			(0x02<< SYSCFG_DIG_METCH_POS)
#define SYSCFG_DIG_METCH_MASK								(SYSCFG_DIG_METCH_BITS<< SYSCFG_DIG_METCH_POS)
#define __SYSCFG_DIG_METCH_GET()							M_REG_GET(SYSCFG_DIG_METCH_REG, SYSCFG_DIG_METCH_POS, SYSCFG_DIG_METCH_BITS)
#define __SYSCFG_DIG_METCH_SET(EN)							M_REG_SET(SYSCFG_DIG_METCH_REG, SYSCFG_DIG_METCH_POS, SYSCFG_DIG_METCH_BITS, EN)
#define __SYSCFG_DIG_METCH_GET_SHIFT()						M_REG_GET_SHIFT(SYSCFG_DIG_METCH_REG, SYSCFG_DIG_METCH_POS, SYSCFG_DIG_METCH_BITS)
#define __SYSCFG_DIG_METCH_SET_SHIFT(POS_EN)				M_REG_SET_SHIFT(SYSCFG_DIG_METCH_REG, SYSCFG_DIG_METCH_POS, SYSCFG_DIG_METCH_BITS, POS_EN)

//TMP_MEAS_EN
#define SYSCFG_TMP_MEAS_EN_REG								CFGR1
#define SYSCFG_TMP_MEAS_EN_POS								(2)
#define SYSCFG_TMP_MEAS_EN_BITS								C_REG_BITS1
#define SYSCFG_TMP_MEAS_EN_DIS								(0x00<< SYSCFG_TMP_MEAS_EN_POS)
#define SYSCFG_TMP_MEAS_EN_EN								(0x01<< SYSCFG_TMP_MEAS_EN_POS)
#define SYSCFG_TMP_MEAS_EN_MASK								(SYSCFG_TMP_MEAS_EN_BITS<< SYSCFG_TMP_MEAS_EN_POS)
#define __SYSCFG_TMP_MEAS_EN_GET()							M_REG_GET(SYSCFG_TMP_MEAS_EN_REG, SYSCFG_TMP_MEAS_EN_POS, SYSCFG_TMP_MEAS_EN_BITS)
#define __SYSCFG_TMP_MEAS_EN_SET(EN)						M_REG_SET(SYSCFG_TMP_MEAS_EN_REG, SYSCFG_TMP_MEAS_EN_POS, SYSCFG_TMP_MEAS_EN_BITS, EN)
#define __SYSCFG_TMP_MEAS_EN_GET_SHIFT()					M_REG_GET_SHIFT(SYSCFG_TMP_MEAS_EN_REG, SYSCFG_TMP_MEAS_EN_POS, SYSCFG_TMP_MEAS_EN_BITS)
#define __SYSCFG_TMP_MEAS_EN_SET_SHIFT(POS_EN)				M_REG_SET_SHIFT(SYSCFG_TMP_MEAS_EN_REG, SYSCFG_TMP_MEAS_EN_POS, SYSCFG_TMP_MEAS_EN_BITS, POS_EN)

//PT34FUNC_2
#define SYSCFG_PT34FUNC_2_REG								CFGR1
#define SYSCFG_PT34FUNC_2_POS								(1)
#define SYSCFG_PT34FUNC_2_BITS								C_REG_BITS1
#define SYSCFG_PT34FUNC_2_RESET								(0x00<< SYSCFG_PT34FUNC_2_POS)
#define SYSCFG_PT34FUNC_2_SET								(0x01<< SYSCFG_PT34FUNC_2_POS)
#define SYSCFG_PT34FUNC_2_MASK								(SYSCFG_PT34FUNC_2_BITS<< SYSCFG_PT34FUNC_2_POS)
#define __SYSCFG_PT34FUNC_2_GET()							M_REG_GET(SYSCFG_PT34FUNC_2_REG, SYSCFG_PT34FUNC_2_POS, SYSCFG_PT34FUNC_2_BITS)
#define __SYSCFG_PT34FUNC_2_SET(SET)						M_REG_SET(SYSCFG_PT34FUNC_2_REG, SYSCFG_PT34FUNC_2_POS, SYSCFG_PT34FUNC_2_BITS, SET)
#define __SYSCFG_PT34FUNC_2_GET_SHIFT()						M_REG_GET_SHIFT(SYSCFG_PT34FUNC_2_REG, SYSCFG_PT34FUNC_2_POS, SYSCFG_PT34FUNC_2_BITS)
#define __SYSCFG_PT34FUNC_2_SET_SHIFT(POS_SET)				M_REG_SET_SHIFT(SYSCFG_PT34FUNC_2_REG, SYSCFG_PT34FUNC_2_POS, SYSCFG_PT34FUNC_2_BITS, POS_SET)

//PT33FUNC_2
#define SYSCFG_PT33FUNC_2_REG								CFGR1
#define SYSCFG_PT33FUNC_2_POS								(0)
#define SYSCFG_PT33FUNC_2_BITS								C_REG_BITS1
#define SYSCFG_PT33FUNC_2_RESET								(0x00<< SYSCFG_PT33FUNC_2_POS)
#define SYSCFG_PT33FUNC_2_SET								(0x01<< SYSCFG_PT33FUNC_2_POS)
#define SYSCFG_PT33FUNC_2_MASK								(SYSCFG_PT33FUNC_2_BITS<< SYSCFG_PT33FUNC_2_POS)
#define __SYSCFG_PT33FUNC_2_GET()							M_REG_GET(SYSCFG_PT33FUNC_2_REG, SYSCFG_PT33FUNC_2_POS, SYSCFG_PT33FUNC_2_BITS)
#define __SYSCFG_PT33FUNC_2_SET(SET)						M_REG_SET(SYSCFG_PT33FUNC_2_REG, SYSCFG_PT33FUNC_2_POS, SYSCFG_PT33FUNC_2_BITS, SET)
#define __SYSCFG_PT33FUNC_2_GET_SHIFT()						M_REG_GET_SHIFT(SYSCFG_PT33FUNC_2_REG, SYSCFG_PT33FUNC_2_POS, SYSCFG_PT33FUNC_2_BITS)
#define __SYSCFG_PT33FUNC_2_SET_SHIFT(POS_SET)				M_REG_SET_SHIFT(SYSCFG_PT33FUNC_2_REG, SYSCFG_PT33FUNC_2_POS, SYSCFG_PT33FUNC_2_BITS, POS_SET)
/**@}*/ /*** end of group syscfg_reg_cfgr1 */

/** 
 * @addtogroup	syscfg_reg_cfgr2	reg: CFGR2 
 * @{
 */
//CFGR2
//PT13FUNC[1:0]
#define SYSCFG_PT13FUNC_REG									CFGR2
#define SYSCFG_PT13FUNC_POS									(6)
#define SYSCFG_PT13FUNC_BITS								C_REG_BITS2
#define SYSCFG_PT13FUNC_GPIO								(0x00<< SYSCFG_PT13FUNC_POS)
#define SYSCFG_PT13FUNC_MASK								(SYSCFG_PT13FUNC_BITS<< SYSCFG_PT13FUNC_POS)
#define __SYSCFG_PT13FUNC_GET()								M_REG_GET(SYSCFG_PT13FUNC_REG, SYSCFG_PT13FUNC_POS, SYSCFG_PT13FUNC_BITS)
#define __SYSCFG_PT13FUNC_SET(CFG)							M_REG_SET(SYSCFG_PT13FUNC_REG, SYSCFG_PT13FUNC_POS, SYSCFG_PT13FUNC_BITS, CFG)
#define __SYSCFG_PT13FUNC_GET_SHIFT()						M_REG_GET_SHIFT(SYSCFG_PT13FUNC_REG, SYSCFG_PT13FUNC_POS, SYSCFG_PT13FUNC_BITS)
#define __SYSCFG_PT13FUNC_SET_SHIFT(POS_CFG)				M_REG_SET_SHIFT(SYSCFG_PT13FUNC_REG, SYSCFG_PT13FUNC_POS, SYSCFG_PT13FUNC_BITS, POS_CFG)

//PT12FUNC[1:0]
#define SYSCFG_PT12FUNC_REG									CFGR2
#define SYSCFG_PT12FUNC_POS									(4)
#define SYSCFG_PT12FUNC_BITS								C_REG_BITS2
#define SYSCFG_PT12FUNC_GPIO								(0x00<< SYSCFG_PT12FUNC_POS)
#define SYSCFG_PT12FUNC_ANA									(0x01<< SYSCFG_PT12FUNC_POS)
#define SYSCFG_PT12FUNC_PWM4								(0x02<< SYSCFG_PT12FUNC_POS)
#define SYSCFG_PT12FUNC_T3IN								(0x03<< SYSCFG_PT12FUNC_POS)
#define SYSCFG_PT12FUNC_MASK								(SYSCFG_PT12FUNC_BITS<< SYSCFG_PT12FUNC_POS)
#define __SYSCFG_PT12FUNC_GET()								M_REG_GET(SYSCFG_PT12FUNC_REG, SYSCFG_PT12FUNC_POS, SYSCFG_PT12FUNC_BITS)
#define __SYSCFG_PT12FUNC_SET(CFG)							M_REG_SET(SYSCFG_PT12FUNC_REG, SYSCFG_PT12FUNC_POS, SYSCFG_PT12FUNC_BITS, CFG)
#define __SYSCFG_PT12FUNC_GET_SHIFT()						M_REG_GET_SHIFT(SYSCFG_PT12FUNC_REG, SYSCFG_PT12FUNC_POS, SYSCFG_PT12FUNC_BITS)
#define __SYSCFG_PT12FUNC_SET_SHIFT(POS_CFG)				M_REG_SET_SHIFT(SYSCFG_PT12FUNC_REG, SYSCFG_PT12FUNC_POS, SYSCFG_PT12FUNC_BITS, POS_CFG)

//PT11FUNC[1:0]
#define SYSCFG_PT11FUNC_REG									CFGR2
#define SYSCFG_PT11FUNC_POS									(2)
#define SYSCFG_PT11FUNC_BITS								C_REG_BITS2
#define SYSCFG_PT11FUNC_GPIO								(0x00<< SYSCFG_PT11FUNC_POS)
#define SYSCFG_PT11FUNC_MASK								(SYSCFG_PT11FUNC_BITS<< SYSCFG_PT11FUNC_POS)
#define __SYSCFG_PT11FUNC_GET()								M_REG_GET(SYSCFG_PT11FUNC_REG, SYSCFG_PT11FUNC_POS, SYSCFG_PT11FUNC_BITS)
#define __SYSCFG_PT11FUNC_SET(CFG)							M_REG_SET(SYSCFG_PT11FUNC_REG, SYSCFG_PT11FUNC_POS, SYSCFG_PT11FUNC_BITS, CFG)
#define __SYSCFG_PT11FUNC_GET_SHIFT()						M_REG_GET_SHIFT(SYSCFG_PT11FUNC_REG, SYSCFG_PT11FUNC_POS, SYSCFG_PT11FUNC_BITS)
#define __SYSCFG_PT11FUNC_SET_SHIFT(POS_CFG)				M_REG_SET_SHIFT(SYSCFG_PT11FUNC_REG, SYSCFG_PT11FUNC_POS, SYSCFG_PT11FUNC_BITS, POS_CFG)

//PT10FUNC[1:0]
#define SYSCFG_PT10FUNC_REG									CFGR2
#define SYSCFG_PT10FUNC_POS									(0)
#define SYSCFG_PT10FUNC_BITS								C_REG_BITS2
#define SYSCFG_PT10FUNC_GPIO								(0x00<< SYSCFG_PT10FUNC_POS)
#define SYSCFG_PT10FUNC_MASK								(SYSCFG_PT10FUNC_BITS<< SYSCFG_PT10FUNC_POS)
#define __SYSCFG_PT10FUNC_GET()								M_REG_GET(SYSCFG_PT10FUNC_REG, SYSCFG_PT10FUNC_POS, SYSCFG_PT10FUNC_BITS)
#define __SYSCFG_PT10FUNC_SET(CFG)							M_REG_SET(SYSCFG_PT10FUNC_REG, SYSCFG_PT10FUNC_POS, SYSCFG_PT10FUNC_BITS, CFG)
#define __SYSCFG_PT10FUNC_GET_SHIFT()						M_REG_GET_SHIFT(SYSCFG_PT10FUNC_REG, SYSCFG_PT10FUNC_POS, SYSCFG_PT10FUNC_BITS)
#define __SYSCFG_PT10FUNC_SET_SHIFT(POS_CFG)				M_REG_SET_SHIFT(SYSCFG_PT10FUNC_REG, SYSCFG_PT10FUNC_POS, SYSCFG_PT10FUNC_BITS, POS_CFG)
/**@}*/ /*** end of group syscfg_reg_cfgr2 */

/** 
 * @addtogroup	syscfg_reg_cfgr3	reg: CFGR3 
 * @{
 */
//CFGR3
//PT17FUNC[1:0]
#define SYSCFG_PT17FUNC_REG									CFGR3
#define SYSCFG_PT17FUNC_POS									(6)
#define SYSCFG_PT17FUNC_BITS								C_REG_BITS2
#define SYSCFG_PT17FUNC_GPIO								(0x00<< SYSCFG_PT17FUNC_POS)
#define SYSCFG_PT17FUNC_MASK								(SYSCFG_PT17FUNC_BITS<< SYSCFG_PT17FUNC_POS)
#define __SYSCFG_PT17FUNC_GET()								M_REG_GET(SYSCFG_PT17FUNC_REG, SYSCFG_PT17FUNC_POS, SYSCFG_PT17FUNC_BITS)
#define __SYSCFG_PT17FUNC_SET(CFG)							M_REG_SET(SYSCFG_PT17FUNC_REG, SYSCFG_PT17FUNC_POS, SYSCFG_PT17FUNC_BITS, CFG)
#define __SYSCFG_PT17FUNC_GET_SHIFT()						M_REG_GET_SHIFT(SYSCFG_PT17FUNC_REG, SYSCFG_PT17FUNC_POS, SYSCFG_PT17FUNC_BITS)
#define __SYSCFG_PT17FUNC_SET_SHIFT(POS_CFG)				M_REG_SET_SHIFT(SYSCFG_PT17FUNC_REG, SYSCFG_PT17FUNC_POS, SYSCFG_PT17FUNC_BITS, POS_CFG)

//PT16FUNC[1:0]
#define SYSCFG_PT16FUNC_REG									CFGR3
#define SYSCFG_PT16FUNC_POS									(4)
#define SYSCFG_PT16FUNC_BITS								C_REG_BITS2
#define SYSCFG_PT16FUNC_GPIO								(0x00<< SYSCFG_PT16FUNC_POS)
#define SYSCFG_PT16FUNC_MASK								(SYSCFG_PT16FUNC_BITS<< SYSCFG_PT16FUNC_POS)
#define __SYSCFG_PT16FUNC_GET()								M_REG_GET(SYSCFG_PT16FUNC_REG, SYSCFG_PT16FUNC_POS, SYSCFG_PT16FUNC_BITS)
#define __SYSCFG_PT16FUNC_SET(CFG)							M_REG_SET(SYSCFG_PT16FUNC_REG, SYSCFG_PT16FUNC_POS, SYSCFG_PT16FUNC_BITS, CFG)
#define __SYSCFG_PT16FUNC_GET_SHIFT()						M_REG_GET_SHIFT(SYSCFG_PT16FUNC_REG, SYSCFG_PT16FUNC_POS, SYSCFG_PT16FUNC_BITS)
#define __SYSCFG_PT16FUNC_SET_SHIFT(POS_CFG)				M_REG_SET_SHIFT(SYSCFG_PT16FUNC_REG, SYSCFG_PT16FUNC_POS, SYSCFG_PT16FUNC_BITS, POS_CFG)

//PT15FUNC[1:0]
#define SYSCFG_PT15FUNC_REG									CFGR3
#define SYSCFG_PT15FUNC_POS									(2)
#define SYSCFG_PT15FUNC_BITS								C_REG_BITS2
#define SYSCFG_PT15FUNC_GPIO								(0x00<< SYSCFG_PT15FUNC_POS)
#define SYSCFG_PT15FUNC_XIN									(0x01<< SYSCFG_PT15FUNC_POS)
#define SYSCFG_PT15FUNC_MASK								(SYSCFG_PT15FUNC_BITS<< SYSCFG_PT15FUNC_POS)
#define __SYSCFG_PT15FUNC_GET()								M_REG_GET(SYSCFG_PT15FUNC_REG, SYSCFG_PT15FUNC_POS, SYSCFG_PT15FUNC_BITS)
#define __SYSCFG_PT15FUNC_SET(CFG)							M_REG_SET(SYSCFG_PT15FUNC_REG, SYSCFG_PT15FUNC_POS, SYSCFG_PT15FUNC_BITS, CFG)
#define __SYSCFG_PT15FUNC_GET_SHIFT()						M_REG_GET_SHIFT(SYSCFG_PT15FUNC_REG, SYSCFG_PT15FUNC_POS, SYSCFG_PT15FUNC_BITS)
#define __SYSCFG_PT15FUNC_SET_SHIFT(POS_CFG)				M_REG_SET_SHIFT(SYSCFG_PT15FUNC_REG, SYSCFG_PT15FUNC_POS, SYSCFG_PT15FUNC_BITS, POS_CFG)

//PT14FUNC[1:0]
#define SYSCFG_PT14FUNC_REG									CFGR3
#define SYSCFG_PT14FUNC_POS									(0)
#define SYSCFG_PT14FUNC_BITS								C_REG_BITS2
#define SYSCFG_PT14FUNC_GPIO								(0x00<< SYSCFG_PT14FUNC_POS)
#define SYSCFG_PT14FUNC_XOUT								(0x01<< SYSCFG_PT14FUNC_POS)
#define SYSCFG_PT14FUNC_MASK								(SYSCFG_PT14FUNC_BITS<< SYSCFG_PT14FUNC_POS)
#define __SYSCFG_PT14FUNC_GET()								M_REG_GET(SYSCFG_PT14FUNC_REG, SYSCFG_PT14FUNC_POS, SYSCFG_PT14FUNC_BITS)
#define __SYSCFG_PT14FUNC_SET(CFG)							M_REG_SET(SYSCFG_PT14FUNC_REG, SYSCFG_PT14FUNC_POS, SYSCFG_PT14FUNC_BITS, CFG)
#define __SYSCFG_PT14FUNC_GET_SHIFT()						M_REG_GET_SHIFT(SYSCFG_PT14FUNC_REG, SYSCFG_PT14FUNC_POS, SYSCFG_PT14FUNC_BITS)
#define __SYSCFG_PT14FUNC_SET_SHIFT(POS_CFG)				M_REG_SET_SHIFT(SYSCFG_PT14FUNC_REG, SYSCFG_PT14FUNC_POS, SYSCFG_PT14FUNC_BITS, POS_CFG)
/**@}*/ /*** end of group syscfg_reg_cfgr3 */

/** 
 * @addtogroup	syscfg_reg_cfgr4	reg: CFGR4 
 * @{
 */
//CFGR4
//PT23FUNC[1:0]
#define SYSCFG_PT23FUNC_REG									CFGR4
#define SYSCFG_PT23FUNC_POS									(6)
#define SYSCFG_PT23FUNC_BITS								C_REG_BITS2
#define SYSCFG_PT23FUNC_GPIO								(0x00<< SYSCFG_PT23FUNC_POS)
#define SYSCFG_PT23FUNC_AIN11								(0x01<< SYSCFG_PT23FUNC_POS)
#define SYSCFG_PT23FUNC_DP_B								(0x02<< SYSCFG_PT23FUNC_POS)
#define SYSCFG_PT23FUNC_PWM2								(0x03<< SYSCFG_PT23FUNC_POS)
#define SYSCFG_PT23FUNC_MASK								(SYSCFG_PT23FUNC_BITS<< SYSCFG_PT23FUNC_POS)
#define __SYSCFG_PT23FUNC_GET()								M_REG_GET(SYSCFG_PT23FUNC_REG, SYSCFG_PT23FUNC_POS, SYSCFG_PT23FUNC_BITS)
#define __SYSCFG_PT23FUNC_SET(CFG)							M_REG_SET(SYSCFG_PT23FUNC_REG, SYSCFG_PT23FUNC_POS, SYSCFG_PT23FUNC_BITS, CFG)
#define __SYSCFG_PT23FUNC_GET_SHIFT()						M_REG_GET_SHIFT(SYSCFG_PT23FUNC_REG, SYSCFG_PT23FUNC_POS, SYSCFG_PT23FUNC_BITS)
#define __SYSCFG_PT23FUNC_SET_SHIFT(POS_CFG)				M_REG_SET_SHIFT(SYSCFG_PT23FUNC_REG, SYSCFG_PT23FUNC_POS, SYSCFG_PT23FUNC_BITS, POS_CFG)

//PT22FUNC[1:0]
#define SYSCFG_PT22FUNC_REG									CFGR4
#define SYSCFG_PT22FUNC_POS									(4)
#define SYSCFG_PT22FUNC_BITS								C_REG_BITS2
#define SYSCFG_PT22FUNC_GPIO								(0x00<< SYSCFG_PT22FUNC_POS)
#define SYSCFG_PT22FUNC_AIN10								(0x01<< SYSCFG_PT22FUNC_POS)
#define SYSCFG_PT22FUNC_MASK								(SYSCFG_PT22FUNC_BITS<< SYSCFG_PT22FUNC_POS)
#define __SYSCFG_PT22FUNC_GET()								M_REG_GET(SYSCFG_PT22FUNC_REG, SYSCFG_PT22FUNC_POS, SYSCFG_PT22FUNC_BITS)
#define __SYSCFG_PT22FUNC_SET(CFG)							M_REG_SET(SYSCFG_PT22FUNC_REG, SYSCFG_PT22FUNC_POS, SYSCFG_PT22FUNC_BITS, CFG)
#define __SYSCFG_PT22FUNC_GET_SHIFT()						M_REG_GET_SHIFT(SYSCFG_PT22FUNC_REG, SYSCFG_PT22FUNC_POS, SYSCFG_PT22FUNC_BITSS)
#define __SYSCFG_PT22FUNC_SET_SHIFT(POS_CFG)				M_REG_SET_SHIFT(SYSCFG_PT22FUNC_REG, SYSCFG_PT22FUNC_POS, SYSCFG_PT22FUNC_BITSS, POS_CFG)

//PT21FUNC[1:0]
#define SYSCFG_PT21FUNC_REG									CFGR4
#define SYSCFG_PT21FUNC_POS									(2)
#define SYSCFG_PT21FUNC_BITS								C_REG_BITS2
#define SYSCFG_PT21FUNC_GPIO								(0x00<< SYSCFG_PT21FUNC_POS)
#define SYSCFG_PT21FUNC_AIN9								(0x01<< SYSCFG_PT21FUNC_POS)
#define SYSCFG_PT21FUNC_MASK								(SYSCFG_PT21FUNC_BITS<< SYSCFG_PT21FUNC_POS)
#define __SYSCFG_PT21FUNC_GET()								M_REG_GET(SYSCFG_PT21FUNC_REG, SYSCFG_PT21FUNC_POS, SYSCFG_PT21FUNC_BITS)
#define __SYSCFG_PT21FUNC_SET(CFG)							M_REG_SET(SYSCFG_PT21FUNC_REG, SYSCFG_PT21FUNC_POS, SYSCFG_PT21FUNC_BITS, CFG)
#define __SYSCFG_PT21FUNC_GET_SHIFT()						M_REG_GET_SHIFT(SYSCFG_PT21FUNC_REG, SYSCFG_PT21FUNC_POS, SYSCFG_PT21FUNC_BITS)
#define __SYSCFG_PT21FUNC_SET_SHIFT(POS_CFG)				M_REG_SET_SHIFT(SYSCFG_PT21FUNC_REG, SYSCFG_PT21FUNC_POS, SYSCFG_PT21FUNC_BITS, POS_CFG)

//PT20FUNC[1:0]
#define SYSCFG_PT20FUNC_REG									CFGR4
#define SYSCFG_PT20FUNC_POS									(0)
#define SYSCFG_PT20FUNC_BITS								C_REG_BITS2
#define SYSCFG_PT20FUNC_GPIO								(0x00<< SYSCFG_PT20FUNC_POS)
#define SYSCFG_PT20FUNC_AIN8								(0x01<< SYSCFG_PT20FUNC_POS)
#define SYSCFG_PT20FUNC_MASK								(SYSCFG_PT20FUNC_BITS<< SYSCFG_PT20FUNC_POS)
#define __SYSCFG_PT20FUNC_GET()								M_REG_GET(SYSCFG_PT20FUNC_REG, SYSCFG_PT20FUNC_POS, SYSCFG_PT20FUNC_BITS)
#define __SYSCFG_PT20FUNC_SET(CFG)							M_REG_SET(SYSCFG_PT20FUNC_REG, SYSCFG_PT20FUNC_POS, SYSCFG_PT20FUNC_BITS, CFG)
#define __SYSCFG_PT20FUNC_GET_SHIFT()						M_REG_GET_SHIFT(SYSCFG_PT20FUNC_REG, SYSCFG_PT20FUNC_POS, SYSCFG_PT20FUNC_BITS)
#define __SYSCFG_PT20FUNC_SET_SHIFT(POS_CFG)				M_REG_SET_SHIFT(SYSCFG_PT20FUNC_REG, SYSCFG_PT20FUNC_POS, SYSCFG_PT20FUNC_BITS, POS_CFG)
/**@}*/ /*** end of group syscfg_reg_cfgr4 */

/** 
 * @addtogroup	syscfg_reg_cfgr5	reg: CFGR5 
 * @{
 */
//CFGR5
//PT26FUNC[1:0]
#define SYSCFG_PT26FUNC_REG									CFGR5
#define SYSCFG_PT26FUNC_POS									(4)
#define SYSCFG_PT26FUNC_BITS								C_REG_BITS2
#define SYSCFG_PT26FUNC_GPIO								(0x00<< SYSCFG_PT26FUNC_POS)
#define SYSCFG_PT26FUNC_AIN14								(0x01<< SYSCFG_PT26FUNC_POS)
#define SYSCFG_PT26FUNC_PWM3L								(0x02<< SYSCFG_PT26FUNC_POS)
#define SYSCFG_PT26FUNC_MASK								(SYSCFG_PT26FUNC_BITS<< SYSCFG_PT26FUNC_POS)
#define __SYSCFG_PT26FUNC_GET()								M_REG_GET(SYSCFG_PT26FUNC_REG, SYSCFG_PT26FUNC_POS, SYSCFG_PT26FUNC_BITS)
#define __SYSCFG_PT26FUNC_SET(CFG)							M_REG_SET(SYSCFG_PT26FUNC_REG, SYSCFG_PT26FUNC_POS, SYSCFG_PT26FUNC_BITS, CFG)
#define __SYSCFG_PT26FUNC_GET_SHIFT()						M_REG_GET_SHIFT(SYSCFG_PT26FUNC_REG, SYSCFG_PT26FUNC_POS, SYSCFG_PT26FUNC_BITS)
#define __SYSCFG_PT26FUNC_SET_SHIFT(POS_CFG)				M_REG_SET_SHIFT(SYSCFG_PT26FUNC_REG, SYSCFG_PT26FUNC_POS, SYSCFG_PT26FUNC_BITS, POS_CFG)

//PT25FUNC[1:0]
#define SYSCFG_PT25FUNC_REG									CFGR5
#define SYSCFG_PT25FUNC_POS									(2)
#define SYSCFG_PT25FUNC_BITS								C_REG_BITS2
#define SYSCFG_PT25FUNC_GPIO								(0x00<< SYSCFG_PT25FUNC_POS)
#define SYSCFG_PT25FUNC_AIN13								(0x01<< SYSCFG_PT25FUNC_POS)
#define SYSCFG_PT25FUNC_PWM3H								(0x02<< SYSCFG_PT25FUNC_POS)
#define SYSCFG_PT25FUNC_ICD									(0x03<< SYSCFG_PT25FUNC_POS)
#define SYSCFG_PT25FUNC_MASK								(SYSCFG_PT25FUNC_BITS<< SYSCFG_PT25FUNC_POS)
#define __SYSCFG_PT25FUNC_GET()								M_REG_GET(SYSCFG_PT25FUNC_REG, SYSCFG_PT25FUNC_POS, SYSCFG_PT25FUNC_BITS)
#define __SYSCFG_PT25FUNC_SET(CFG)							M_REG_SET(SYSCFG_PT25FUNC_REG, SYSCFG_PT25FUNC_POS, SYSCFG_PT25FUNC_BITS, CFG)
#define __SYSCFG_PT25FUNC_GET_SHIFT()						M_REG_GET_SHIFT(SYSCFG_PT25FUNC_REG, SYSCFG_PT25FUNC_POS, SYSCFG_PT25FUNC_BITS)
#define __SYSCFG_PT25FUNC_SET_SHIFT(POS_CFG)				M_REG_SET_SHIFT(SYSCFG_PT25FUNC_REG, SYSCFG_PT25FUNC_POS, SYSCFG_PT25FUNC_BITS, POS_CFG)

//PT24FUNC[1:0]
#define SYSCFG_PT24FUNC_REG									CFGR5
#define SYSCFG_PT24FUNC_POS									(0)
#define SYSCFG_PT24FUNC_BITS								C_REG_BITS2
#define SYSCFG_PT24FUNC_GPIO								(0x00<< SYSCFG_PT24FUNC_POS)
#define SYSCFG_PT24FUNC_AIN12								(0x01<< SYSCFG_PT24FUNC_POS)
#define SYSCFG_PT24FUNC_DM_B								(0x02<< SYSCFG_PT24FUNC_POS)
#define SYSCFG_PT24FUNC_MASK								(SYSCFG_PT24FUNC_BITS<< SYSCFG_PT24FUNC_POS)
#define __SYSCFG_PT24FUNC_GET()								M_REG_GET(SYSCFG_PT24FUNC_REG, SYSCFG_PT24FUNC_POS, SYSCFG_PT24FUNC_BITS)
#define __SYSCFG_PT24FUNC_SET(CFG)							M_REG_SET(SYSCFG_PT24FUNC_REG, SYSCFG_PT24FUNC_POS, SYSCFG_PT24FUNC_BITS, CFG)
#define __SYSCFG_PT24FUNC_GET_SHIFT()						M_REG_GET_SHIFT(SYSCFG_PT24FUNC_REG, SYSCFG_PT24FUNC_POS, SYSCFG_PT24FUNC_BITS)
#define __SYSCFG_PT24FUNC_SET_SHIFT(POS_CFG)				M_REG_SET_SHIFT(SYSCFG_PT24FUNC_REG, SYSCFG_PT24FUNC_POS, SYSCFG_PT24FUNC_BITS, POS_CFG)
/**@}*/ /*** end of group syscfg_reg_cfgr5 */

/** 
 * @addtogroup	syscfg_reg_cfgr6	reg: CFGR6 
 * @{
 */
//CFGR6
//PT33FUNC[1:0]
#define SYSCFG_PT33FUNC_REG									CFGR6
#define SYSCFG_PT33FUNC_POS									(6)
#define SYSCFG_PT33FUNC_BITS								C_REG_BITS2
#define SYSCFG_PT33FUNC_GPIO								(0x00<< SYSCFG_PT33FUNC_POS)
#define SYSCFG_PT33FUNC_AIN3_CC1B							(0x01<< SYSCFG_PT33FUNC_POS)
#define SYSCFG_PT33FUNC_UART_TX								(0x02<< SYSCFG_PT33FUNC_POS)
#define SYSCFG_PT33FUNC_DP_D								(0x03<< SYSCFG_PT33FUNC_POS)
#define SYSCFG_PT33FUNC_MASK								(SYSCFG_PT33FUNC_BITS<< SYSCFG_PT33FUNC_POS)
#define __SYSCFG_PT33FUNC_GET()								M_REG_GET(SYSCFG_PT33FUNC_REG, SYSCFG_PT33FUNC_POS, SYSCFG_PT33FUNC_BITS)
#define __SYSCFG_PT33FUNC_SET(CFG)							M_REG_SET(SYSCFG_PT33FUNC_REG, SYSCFG_PT33FUNC_POS, SYSCFG_PT33FUNC_BITS, CFG)
#define __SYSCFG_PT33FUNC_GET_SHIFT()						M_REG_GET_SHIFT(SYSCFG_PT33FUNC_REG, SYSCFG_PT33FUNC_POS, SYSCFG_PT33FUNC_BITS)
#define __SYSCFG_PT33FUNC_SET_SHIFT(POS_CFG)				M_REG_SET_SHIFT(SYSCFG_PT33FUNC_REG, SYSCFG_PT33FUNC_POS, SYSCFG_PT33FUNC_BITS, POS_CFG)

//PT32FUNC[1:0]
#define SYSCFG_PT32FUNC_REG									CFGR6
#define SYSCFG_PT32FUNC_POS									(4)
#define SYSCFG_PT32FUNC_BITS								C_REG_BITS2
#define SYSCFG_PT32FUNC_GPIO								(0x00<< SYSCFG_PT32FUNC_POS)
#define SYSCFG_PT32FUNC_AIN2								(0x01<< SYSCFG_PT32FUNC_POS)
#define SYSCFG_PT32FUNC_UART_RX								(0x02<< SYSCFG_PT32FUNC_POS)
#define SYSCFG_PT32FUNC_DM_A								(0x03<< SYSCFG_PT32FUNC_POS)
#define SYSCFG_PT32FUNC_MASK								(SYSCFG_PT32FUNC_BITS<< SYSCFG_PT32FUNC_POS)
#define __SYSCFG_PT32FUNC_GET()								M_REG_GET(SYSCFG_PT32FUNC_REG, SYSCFG_PT32FUNC_POS, SYSCFG_PT32FUNC_BITS)
#define __SYSCFG_PT32FUNC_SET(CFG)							M_REG_SET(SYSCFG_PT32FUNC_REG, SYSCFG_PT32FUNC_POS, SYSCFG_PT32FUNC_BITS, CFG)
#define __SYSCFG_PT32FUNC_GET_SHIFT()						M_REG_GET_SHIFT(SYSCFG_PT32FUNC_REG, SYSCFG_PT32FUNC_POS, SYSCFG_PT32FUNC_BITS)
#define __SYSCFG_PT32FUNC_SET_SHIFT(POS_CFG)				M_REG_SET_SHIFT(SYSCFG_PT32FUNC_REG, SYSCFG_PT32FUNC_POS, SYSCFG_PT32FUNC_BITS, POS_CFG)

//PT31FUNC[1:0]
#define SYSCFG_PT31FUNC_REG									CFGR6
#define SYSCFG_PT31FUNC_POS									(2)
#define SYSCFG_PT31FUNC_BITS								C_REG_BITS2
#define SYSCFG_PT31FUNC_GPIO								(0x00<< SYSCFG_PT31FUNC_POS)
#define SYSCFG_PT31FUNC_AIN1								(0x01<< SYSCFG_PT31FUNC_POS)
#define SYSCFG_PT31FUNC_UART_TX								(0x02<< SYSCFG_PT31FUNC_POS)
#define SYSCFG_PT31FUNC_DP_A								(0x03<< SYSCFG_PT31FUNC_POS)
#define SYSCFG_PT31FUNC_MASK								(SYSCFG_PT31FUNC_BITS<< SYSCFG_PT31FUNC_POS)
#define __SYSCFG_PT31FUNC_GET()								M_REG_GET(SYSCFG_PT31FUNC_REG, SYSCFG_PT31FUNC_POS, SYSCFG_PT31FUNC_BITS)
#define __SYSCFG_PT31FUNC_SET(CFG)							M_REG_SET(SYSCFG_PT31FUNC_REG, SYSCFG_PT31FUNC_POS, SYSCFG_PT31FUNC_BITS, CFG)
#define __SYSCFG_PT31FUNC_GET_SHIFT()						M_REG_GET_SHIFT(SYSCFG_PT31FUNC_REG, SYSCFG_PT31FUNC_POS, SYSCFG_PT31FUNC_BITS)
#define __SYSCFG_PT31FUNC_SET_SHIFT(POS_CFG)				M_REG_SET_SHIFT(SYSCFG_PT31FUNC_REG, SYSCFG_PT31FUNC_POS, SYSCFG_PT31FUNC_BITS, POS_CFG)

//PT30FUNC[1:0]
#define SYSCFG_PT30FUNC_REG									CFGR6
#define SYSCFG_PT30FUNC_POS									(0)
#define SYSCFG_PT30FUNC_BITS								C_REG_BITS2
#define SYSCFG_PT30FUNC_GPIO								(0x00<< SYSCFG_PT30FUNC_POS)
#define SYSCFG_PT30FUNC_AIA									(0x01<< SYSCFG_PT30FUNC_POS)
#define SYSCFG_PT30FUNC_MASK								(SYSCFG_PT30FUNC_BITS<< SYSCFG_PT30FUNC_POS)
#define __SYSCFG_PT30FUNC_GET()								M_REG_GET(SYSCFG_PT30FUNC_REG, SYSCFG_PT30FUNC_POS, SYSCFG_PT30FUNC_BITS)
#define __SYSCFG_PT30FUNC_SET(CFG)							M_REG_SET(SYSCFG_PT30FUNC_REG, SYSCFG_PT30FUNC_POS, SYSCFG_PT30FUNC_BITS, CFG)
#define __SYSCFG_PT30FUNC_GET_SHIFT()						M_REG_GET_SHIFT(SYSCFG_PT30FUNC_REG, SYSCFG_PT30FUNC_POS, SYSCFG_PT30FUNC_BITS)
#define __SYSCFG_PT30FUNC_SET_SHIFT(POS_CFG)				M_REG_SET_SHIFT(SYSCFG_PT30FUNC_REG, SYSCFG_PT30FUNC_POS, SYSCFG_PT30FUNC_BITS, POS_CFG)
/**@}*/ /*** end of group syscfg_reg_cfgr6 */

/** 
 * @addtogroup	syscfg_reg_cfgr7	reg: CFGR7 
 * @{
 */
//CFGR7
//PT37FUNC[1:0]
#define SYSCFG_PT37FUNC_REG									CFGR7
#define SYSCFG_PT37FUNC_POS									(6)
#define SYSCFG_PT37FUNC_BITS								C_REG_BITS2
#define SYSCFG_PT37FUNC_GPIO								(0x00<< SYSCFG_PT37FUNC_POS)
#define SYSCFG_PT37FUNC_AIN7								(0x01<< SYSCFG_PT37FUNC_POS)
#define SYSCFG_PT37FUNC_MASK								(SYSCFG_PT37FUNC_BITS<< SYSCFG_PT37FUNC_POS)
#define __SYSCFG_PT37FUNC_GET()								M_REG_GET(SYSCFG_PT37FUNC_REG, SYSCFG_PT37FUNC_POS, SYSCFG_PT37FUNC_BITS)
#define __SYSCFG_PT37FUNC_SET(CFG)							M_REG_SET(SYSCFG_PT37FUNC_REG, SYSCFG_PT37FUNC_POS, SYSCFG_PT37FUNC_BITS, CFG)
#define __SYSCFG_PT37FUNC_GET_SHIFT()						M_REG_GET_SHIFT(SYSCFG_PT37FUNC_REG, SYSCFG_PT37FUNC_POS, SYSCFG_PT37FUNC_BITS)
#define __SYSCFG_PT37FUNC_SET_SHIFT(POS_CFG)				M_REG_SET_SHIFT(SYSCFG_PT37FUNC_REG, SYSCFG_PT37FUNC_POS, SYSCFG_PT37FUNC_BITS, POS_CFG)

//PT36FUNC[1:0]
#define SYSCFG_PT36FUNC_REG									CFGR7
#define SYSCFG_PT36FUNC_POS									(4)
#define SYSCFG_PT36FUNC_BITS								C_REG_BITS2
#define SYSCFG_PT36FUNC_GPIO								(0x00<< SYSCFG_PT36FUNC_POS)
#define SYSCFG_PT36FUNC_AIN6								(0x01<< SYSCFG_PT36FUNC_POS)
#define SYSCFG_PT36FUNC_UART_RX								(0x02<< SYSCFG_PT36FUNC_POS)
#define SYSCFG_PT36FUNC_DM_C								(0x03<< SYSCFG_PT36FUNC_POS)
#define SYSCFG_PT36FUNC_MASK								(SYSCFG_PT36FUNC_BITS<< SYSCFG_PT36FUNC_POS)
#define __SYSCFG_PT36FUNC_GET()								M_REG_GET(SYSCFG_PT36FUNC_REG, SYSCFG_PT36FUNC_POS, SYSCFG_PT36FUNC_BITS)
#define __SYSCFG_PT36FUNC_SET(CFG)							M_REG_SET(SYSCFG_PT36FUNC_REG, SYSCFG_PT36FUNC_POS, SYSCFG_PT36FUNC_BITS, CFG)
#define __SYSCFG_PT36FUNC_GET_SHIFT()						M_REG_GET_SHIFT(SYSCFG_PT36FUNC_REG, SYSCFG_PT36FUNC_POS, SYSCFG_PT36FUNC_BITS)
#define __SYSCFG_PT36FUNC_SET_SHIFT(POS_CFG)				M_REG_SET_SHIFT(SYSCFG_PT36FUNC_REG, SYSCFG_PT36FUNC_POS, SYSCFG_PT36FUNC_BITS, POS_CFG)

//PT35FUNC[1:0]
#define SYSCFG_PT35FUNC_REG									CFGR7
#define SYSCFG_PT35FUNC_POS									(2)
#define SYSCFG_PT35FUNC_BITS								C_REG_BITS2
#define SYSCFG_PT35FUNC_GPIO								(0x00<< SYSCFG_PT35FUNC_POS)
#define SYSCFG_PT35FUNC_AIN5								(0x01<< SYSCFG_PT35FUNC_POS)
#define SYSCFG_PT35FUNC_UART_TX								(0x02<< SYSCFG_PT35FUNC_POS)
#define SYSCFG_PT35FUNC_DP_C								(0x03<< SYSCFG_PT35FUNC_POS)
#define SYSCFG_PT35FUNC_MASK								(SYSCFG_PT35FUNC_BITS<< SYSCFG_PT35FUNC_POS)
#define __SYSCFG_PT35FUNC_GET()								M_REG_GET(SYSCFG_PT35FUNC_REG, SYSCFG_PT35FUNC_POS, SYSCFG_PT35FUNC_BITS)
#define __SYSCFG_PT35FUNC_SET(CFG)							M_REG_SET(SYSCFG_PT35FUNC_REG, SYSCFG_PT35FUNC_POS, SYSCFG_PT35FUNC_BITS, CFG)
#define __SYSCFG_PT35FUNC_GET_SHIFT()						M_REG_GET_SHIFT(SYSCFG_PT35FUNC_REG, SYSCFG_PT35FUNC_POS, SYSCFG_PT35FUNC_BITS)
#define __SYSCFG_PT35FUNC_SET_SHIFT(POS_CFG)				M_REG_SET_SHIFT(SYSCFG_PT35FUNC_REG, SYSCFG_PT35FUNC_POS, SYSCFG_PT35FUNC_BITS, POS_CFG)

//PT34FUNC[1:0]
#define SYSCFG_PT34FUNC_REG									CFGR7
#define SYSCFG_PT34FUNC_POS									(0)
#define SYSCFG_PT34FUNC_BITS								C_REG_BITS2
#define SYSCFG_PT34FUNC_GPIO								(0x00<< SYSCFG_PT34FUNC_POS)
#define SYSCFG_PT34FUNC_AIN4_CC2B							(0x01<< SYSCFG_PT34FUNC_POS)
#define SYSCFG_PT34FUNC_UART_RX								(0x02<< SYSCFG_PT34FUNC_POS)
#define SYSCFG_PT34FUNC_DM_D								(0x03<< SYSCFG_PT34FUNC_POS)
#define SYSCFG_PT34FUNC_MASK								(SYSCFG_PT34FUNC_BITS<< SYSCFG_PT34FUNC_POS)
#define __SYSCFG_PT34FUNC_GET()								M_REG_GET(SYSCFG_PT34FUNC_REG, SYSCFG_PT34FUNC_POS, SYSCFG_PT34FUNC_BITS)
#define __SYSCFG_PT34FUNC_SET(CFG)							M_REG_SET(SYSCFG_PT34FUNC_REG, SYSCFG_PT34FUNC_POS, SYSCFG_PT34FUNC_BITS, CFG)
#define __SYSCFG_PT34FUNC_GET_SHIFT()						M_REG_GET_SHIFT(SYSCFG_PT34FUNC_REG, SYSCFG_PT34FUNC_POS, SYSCFG_PT34FUNC_BITS)
#define __SYSCFG_PT34FUNC_SET_SHIFT(POS_CFG)				M_REG_SET_SHIFT(SYSCFG_PT34FUNC_REG, SYSCFG_PT34FUNC_POS, SYSCFG_PT34FUNC_BITS, POS_CFG)
/**@}*/ /*** end of group syscfg_reg_cfgr7 */

/** 
 * @addtogroup	syscfg_reg_cfgr8	reg: CFGR8 
 * @{
 */
//CFGR8
//CMPVR_EN
#define SYSCFG_CMPVR_EN_REG									CFGR8
#define SYSCFG_CMPVR_EN_POS									(7)
#define SYSCFG_CMPVR_EN_BITS								C_REG_BITS1
#define SYSCFG_CMPVR_EN_DIS									(0x00<< SYSCFG_CMPVR_EN_POS)
#define SYSCFG_CMPVR_EN_EN									(0x01<< SYSCFG_CMPVR_EN_POS)
#define SYSCFG_CMPVR_EN_MASK								(SYSCFG_CMPVR_EN_BITS<< SYSCFG_CMPVR_EN_POS)
#define __SYSCFG_CMPVR_EN_GET()								M_REG_GET(SYSCFG_CMPVR_EN_REG, SYSCFG_CMPVR_EN_POS, SYSCFG_CMPVR_EN_BITS)
#define __SYSCFG_CMPVR_EN_SET(EN)							M_REG_SET(SYSCFG_CMPVR_EN_REG, SYSCFG_CMPVR_EN_POS, SYSCFG_CMPVR_EN_BITS, EN)
#define __SYSCFG_CMPVR_EN_GET_SHIFT()						M_REG_GET_SHIFT(SYSCFG_CMPVR_EN_REG, SYSCFG_CMPVR_EN_POS, SYSCFG_CMPVR_EN_BITS)
#define __SYSCFG_CMPVR_EN_SET_SHIFT(POS_EN)					M_REG_SET_SHIFT(SYSCFG_CMPVR_EN_REG, SYSCFG_CMPVR_EN_POS, SYSCFG_CMPVR_EN_BITS, POS_EN)

//CMP1VRS[2:0]
#define SYSCFG_CMP1VRS_REG									CFGR8
#define SYSCFG_CMP1VRS_POS									(4)
#define SYSCFG_CMP1VRS_BITS									C_REG_BITS3
#define SYSCFG_CMP1VRS_0V2									(0x00<< SYSCFG_CMP1VRS_POS)
#define SYSCFG_CMP1VRS_0V4									(0x01<< SYSCFG_CMP1VRS_POS)
#define SYSCFG_CMP1VRS_0V66									(0x02<< SYSCFG_CMP1VRS_POS)
#define SYSCFG_CMP1VRS_0V8									(0x03<< SYSCFG_CMP1VRS_POS)
#define SYSCFG_CMP1VRS_1V23									(0x04<< SYSCFG_CMP1VRS_POS)
#define SYSCFG_CMP1VRS_1V58									(0x05<< SYSCFG_CMP1VRS_POS)
#define SYSCFG_CMP1VRS_2V18									(0x06<< SYSCFG_CMP1VRS_POS)
#define SYSCFG_CMP1VRS_2V6									(0x07<< SYSCFG_CMP1VRS_POS)
#define SYSCFG_CMP1VRS_MASK									(SYSCFG_CMP1VRS_BITS<< SYSCFG_CMP1VRS_POS)
#define __SYSCFG_CMP1VRS_GET()								M_REG_GET(SYSCFG_CMP1VRS_REG, SYSCFG_CMP1VRS_POS, SYSCFG_CMP1VRS_BITS)
#define __SYSCFG_CMP1VRS_SET(CFG)							M_REG_SET(SYSCFG_CMP1VRS_REG, SYSCFG_CMP1VRS_POS, SYSCFG_CMP1VRS_BITS, CFG)
#define __SYSCFG_CMP1VRS_GET_SHIFT()						M_REG_GET_SHIFT(SYSCFG_CMP1VRS_REG, SYSCFG_CMP1VRS_POS, SYSCFG_CMP1VRS_BITS)
#define __SYSCFG_CMP1VRS_SET_SHIFT(POS_CFG)					M_REG_SET_SHIFT(SYSCFG_CMP1VRS_REG, SYSCFG_CMP1VRS_POS, SYSCFG_CMP1VRS_BITS, POS_CFG)

//CMP0VRS[3:0]
#define SYSCFG_CMP0VRS_REG									CFGR8
#define SYSCFG_CMP0VRS_POS									(0)
#define SYSCFG_CMP0VRS_BITS									C_REG_BITS4
#define SYSCFG_CMP0VRS_0V									(0x00<< SYSCFG_CMP0VRS_POS)
#define SYSCFG_CMP0VRS_0V32									(0x01<< SYSCFG_CMP0VRS_POS)
#define SYSCFG_CMP0VRS_0V6									(0x02<< SYSCFG_CMP0VRS_POS)
#define SYSCFG_CMP0VRS_1V0									(0x03<< SYSCFG_CMP0VRS_POS)
#define SYSCFG_CMP0VRS_2V0									(0x04<< SYSCFG_CMP0VRS_POS)
#define SYSCFG_CMP0VRS_2V7									(0x05<< SYSCFG_CMP0VRS_POS)
#define SYSCFG_CMP0VRS_3V0									(0x06<< SYSCFG_CMP0VRS_POS)
#define SYSCFG_CMP0VRS_3V3									(0x07<< SYSCFG_CMP0VRS_POS)
#define SYSCFG_CMP0VRS_1V2									(0x08<< SYSCFG_CMP0VRS_POS)
#define SYSCFG_CMP0VRS_2V4									(0x0C<< SYSCFG_CMP0VRS_POS)
#define SYSCFG_CMP0VRS_MASK									(SYSCFG_CMP0VRS_BITS<< SYSCFG_CMP0VRS_POS)
#define __SYSCFG_CMP0VRS_GET()								M_REG_GET(SYSCFG_CMP0VRS_REG, SYSCFG_CMP0VRS_POS, SYSCFG_CMP0VRS_BITS)
#define __SYSCFG_CMP0VRS_SET(CFG)							M_REG_SET(SYSCFG_CMP0VRS_REG, SYSCFG_CMP0VRS_POS, SYSCFG_CMP0VRS_BITS, CFG)
#define __SYSCFG_CMP0VRS_GET_SHIFT()						M_REG_GET_SHIFT(SYSCFG_CMP0VRS_REG, SYSCFG_CMP0VRS_POS, SYSCFG_CMP0VRS_BITS)
#define __SYSCFG_CMP0VRS_SET_SHIFT(POS_CFG)					M_REG_SET_SHIFT(SYSCFG_CMP0VRS_REG, SYSCFG_CMP0VRS_POS, SYSCFG_CMP0VRS_BITS, POS_CFG)
/**@}*/ /*** end of group syscfg_reg_cfgr8 */
/*******************************************************************************/




/******************************** dividing line ********************************/
/** 
 * @addtogroup csu39fx10_sdk_chip_fwlib_syscfg_cfg	syscfg_config
 * @{
 */
/** 
 * @name syscfg config
 * @{
 */
/**
 * @details <b>CFG_SYSCFG_VTHSEL</b>
 * - <b>Features: </b> input logic level voltage control signal
 * - <b>Param: </b>
 * | config	| Descriptions					|
 * | :----:	| :----:						|
 * | 0*		| VIN_H= 0P6VDD, VIN_L= 0P4VDD	|
 * | 1		| VIN_H= 0P5VDD, VIN_L= 0P5VDD	|
 
 */
// #define	CFG_SYSCFG_VTHSEL				(0)			///< {0, 1}
#define	CFG_SYSCFG_VTHSEL				(0)			///< {0, 1}

/**
 * @details <b>CFG_SYSCFG_TMP_MEAS_EN</b>
 * - <b>Features: </b> temperature resistance enable control
 * - <b>Param: </b>
 * | config	| Descriptions	|
 * | :----:	| :----:		|
 * | 0*		| enable		|
 * | 1		| disable		|
 */
#define	CFG_SYSCFG_TMP_MEAS_EN			(0)			///< 0-> disable, 1-> enable

/**
 * @details <b>CFG_SYSCFG_PINMUX_PT10</b>
 * - <b>Features: </b> pt1.0 pin_mux
 * - <b>Param: </b>
 * | config	| Descriptions	|
 * | :----:	| :----:		|
 * | 0*		| GPIO			|
 * | 1		| Reserved		|
 * | 2		| Reserved		|
 * | 3		| Reserved		|
 */
#define	CFG_SYSCFG_PINMUX_PT10			(0)			///< {0~ 3}

/**
 * @details <b>CFG_SYSCFG_PINMUX_PT11</b>
 * - <b>Features: </b> pt1.1 pin_mux
 * - <b>Param: </b>
 * | config	| Descriptions	|
 * | :----:	| :----:		|
 * | 0*		| GPIO			|
 * | 1		| Reserved		|
 * | 2		| Reserved		|
 * | 3		| Reserved		|
 */
#define	CFG_SYSCFG_PINMUX_PT11			(0)			///< {0~ 3}

/**
 * @details <b>CFG_SYSCFG_PINMUX_PT12</b>
 * - <b>Features: </b> pt1.2 pin_mux
 * - <b>Param: </b>
 * | config	| Descriptions	|
 * | :----:	| :----:		|
 * | 0*		| GPIO			|
 * | 1		| Analog_port	|
 * | 2		| PWM4_output	|
 * | 3		| TIMER3_IN		|
 */
//#define	CFG_SYSCFG_PINMUX_PT12			(2)			///< {0~ 3}
#define	CFG_SYSCFG_PINMUX_PT12			(0)			///< {0~ 3}

/**
 * @details <b>CFG_SYSCFG_PINMUX_PT13</b>
 * - <b>Features: </b> pt1.3 pin_mux
 * - <b>Param: </b>
 * | config	| Descriptions	|
 * | :----:	| :----:		|
 * | 0*		| GPIO			|
 * | 1		| Reserved		|
 * | 2		| Reserved		|
 * | 3		| Reserved		|
 */
#define	CFG_SYSCFG_PINMUX_PT13			(0)			///< {0~ 3}

/**
 * @details <b>CFG_SYSCFG_PINMUX_PT14</b>
 * - <b>Features: </b> pt1.4 pin_mux
 * - <b>Param: </b>
 * | config	| Descriptions	|
 * | :----:	| :----:		|
 * | 0*		| GPIO_SWDIO	|
 * | 1		| XOUT			|
 * | 2		| Reserved		|
 * | 3		| Reserved		|
 */
#define	CFG_SYSCFG_PINMUX_PT14			(0)			///< {0~ 3}

/**
 * @details <b>CFG_SYSCFG_PINMUX_PT15</b>
 * - <b>Features: </b> pt1.5 pin_mux
 * - <b>Param: </b>
 * | config	| Descriptions	|
 * | :----:	| :----:		|
 * | 0*		| GPIO_SWDCLK	|
 * | 1		| XIN			|
 * | 2		| Reserved		|
 * | 3		| Reserved		|
 */
#define	CFG_SYSCFG_PINMUX_PT15			(0)			///< {0~ 3}

/**
 * @details <b>CFG_SYSCFG_PINMUX_PT16</b>
 * - <b>Features: </b> pt1.6 pin_mux
 * - <b>Param: </b>
 * | config	| Descriptions	|
 * | :----:	| :----:		|
 * | 0*		| GPIO			|
 * | 1		| Reserved		|
 * | 2		| Reserved		|
 * | 3		| Reserved		|
 */
#define	CFG_SYSCFG_PINMUX_PT16			(0)			///< {0~ 3}

/**
 * @details <b>CFG_SYSCFG_PINMUX_PT17</b>
 * - <b>Features: </b> pt1.7 pin_mux
 * - <b>Param: </b>
 * | config	| Descriptions	|
 * | :----:	| :----:		|
 * | 0*		| GPIO			|
 * | 1		| Reserved		|
 * | 2		| Reserved		|
 * | 3		| Reserved		|
 */
#define	CFG_SYSCFG_PINMUX_PT17			(0)			///< {0~ 3}

/**
 * @details <b>CFG_SYSCFG_PINMUX_PT20</b>
 * - <b>Features: </b> pt2.0 pin_mux
 * - <b>Param: </b>
 * | config	| Descriptions		|
 * | :----:	| :----:			|
 * | 0*		| GPIO				|
 * | 1		| Analog_port(AIN8)	|
 * | 2		| Reserved			|
 * | 3		| Reserved			|
 */
#define	CFG_SYSCFG_PINMUX_PT20			(1)			///< {0~ 3}
//#define	CFG_SYSCFG_PINMUX_PT20			(0)			///< {0~ 3}
/**
 * @details <b>CFG_SYSCFG_PINMUX_PT21</b>
 * - <b>Features: </b> pt2.1 pin_mux
 * - <b>Param: </b>
 * | config	| Descriptions		|
 * | :----:	| :----:			|
 * | 0*		| GPIO				|
 * | 1		| Analog_port(AIN9)	|
 * | 2		| Reserved			|
 * | 3		| Reserved			|
 */
#define	CFG_SYSCFG_PINMUX_PT21			(1)			///< {0~ 3}

/**
 * @details <b>CFG_SYSCFG_PINMUX_PT22</b>
 * - <b>Features: </b> pt2.2 pin_mux
 * - <b>Param: </b>
 * | config	| Descriptions			|
 * | :----:	| :----:				|
 * | 0*		| GPIO					|
 * | 1		| Analog_port(AIN10)	|
 * | 2		| Reserved				|
 * | 3		| Reserved				|
 */
//#define	CFG_SYSCFG_PINMUX_PT22			(1)			///< {0~ 3}
#define	CFG_SYSCFG_PINMUX_PT22			(0)			///< {0~ 3}
/**
 * @details <b>CFG_SYSCFG_PINMUX_PT23</b>
 * - <b>Features: </b> pt2.3 pin_mux
 * - <b>Param: </b>
 * | config	| Descriptions			|
 * | :----:	| :----:				|
 * | 0*		| GPIO					|
 * | 1		| Analog_port(AIN11)	|
 * | 2		| DP_B					|
 * | 3		| PWM2_output			|
 */
#define	CFG_SYSCFG_PINMUX_PT23			(1)			///< {0~ 3}

/**
 * @details <b>CFG_SYSCFG_PINMUX_PT24</b>
 * - <b>Features: </b> pt2.4 pin_mux
 * - <b>Param: </b>
 * | config	| Descriptions			|
 * | :----:	| :----:				|
 * | 0*		| GPIO					|
 * | 1		| Analog_port(AIN12)	|
 * | 2		| DM_B					|
 * | 3		| PWM3_output			|
 */
//#define	CFG_SYSCFG_PINMUX_PT24			(0)			///< {0~ 3}
#define	CFG_SYSCFG_PINMUX_PT24			(1)			///< {0~ 3}

/**
 * @details <b>CFG_SYSCFG_PINMUX_PT25</b>
 * - <b>Features: </b> pt2.5 pin_mux
 * - <b>Param: </b>
 * | config	| Descriptions			|
 * | :----:	| :----:				|
 * | 0*		| GPIO					|
 * | 1		| Analog_port(AIN13)	|
 * | 2		| PWM3H					|
 * | 3		| ICD					|
 */
//#define	CFG_SYSCFG_PINMUX_PT25			(3)			///< {0~ 3}
#define	CFG_SYSCFG_PINMUX_PT25			(0)			///< {0~ 3}


/**
 * @details <b>CFG_SYSCFG_PINMUX_PT26</b>
 * - <b>Features: </b> pt2.6 pin_mux
 * - <b>Param: </b>
 * | config	| Descriptions			|
 * | :----:	| :----:				|
 * | 0*		| GPIO					|
 * | 1		| Analog_port(AIN14)	|
 * | 2		| PWM3L					|
 * | 3		| Reserved				|
 */
//#define	CFG_SYSCFG_PINMUX_PT26			(1)			///< {0~ 3}
#define	CFG_SYSCFG_PINMUX_PT26			(0)			///< {0~ 3}

/**
 * @details <b>CFG_SYSCFG_PINMUX_PT30</b>
 * - <b>Features: </b> pt3.0 pin_mux
 * - <b>Param: </b>
 * | config	| Descriptions					|
 * | :----:	| :----:						|
 * | 0*		| GPIO							|
 * | 1		| Analog_port(AIN0, VREF, NTC)	|
 * | 2		| Reserved						|
 * | 3		| Reserved						|
 */
//#define	CFG_SYSCFG_PINMUX_PT30			(0)			///< {0~ 3}
#define	CFG_SYSCFG_PINMUX_PT30			(1)			///< {0~ 3}
/**
 * @details <b>CFG_SYSCFG_PINMUX_PT31</b>
 * - <b>Features: </b> pt3.1 pin_mux
 * - <b>Param: </b>
 * | config	| Descriptions		|
 * | :----:	| :----:			|
 * | 0*		| GPIO				|
 * | 1		| Analog_port(AIN1)	|
 * | 2		| UART_TX			|
 * | 3		| DP_A				|
 */
//#define	CFG_SYSCFG_PINMUX_PT31			(0)			///< {0~ 3}
#define	CFG_SYSCFG_PINMUX_PT31			(1)			///< {0~ 3}
/**
 * @details <b>CFG_SYSCFG_PINMUX_PT32</b>
 * - <b>Features: </b> pt3.2 pin_mux
 * - <b>Param: </b>
 * | config	| Descriptions		|
 * | :----:	| :----:			|
 * | 0*		| GPIO				|
 * | 1		| Analog_port(AIN2)	|
 * | 2		| UART_RX			|
 * | 3		| DM_A				|
 */
#define	CFG_SYSCFG_PINMUX_PT32			(3)			///< {0~ 3}

/**
 * @details <b>CFG_SYSCFG_PINMUX_PT33</b>
 * - <b>Features: </b> pt3.3 pin_mux
 * - <b>Param: </b>
 * | config	| Descriptions				|
 * | :----:	| :----:					|
 * | 0*		| GPIO						|
 * | 1		| Analog_port(AIN3, CC1_B)	|
 * | 2		| UART_TX					|
 * | 3		| DP_D						|
 */
#define	CFG_SYSCFG_PINMUX_PT33			(0)			///< {0~ 3}

/**
 * @details <b>CFG_SYSCFG_PINMUX_PT34</b>
 * - <b>Features: </b> pt3.4 pin_mux
 * - <b>Param: </b>
 * | config	| Descriptions				|
 * | :----:	| :----:					|
 * | 0*		| GPIO						|
 * | 1		| Analog_port(AIN4, CC2_B)	|
 * | 2		| UART_RX					|
 * | 3		| DM_D						|
 */
#define	CFG_SYSCFG_PINMUX_PT34			(0)			///< {0~ 3}

/**
 * @details <b>CFG_SYSCFG_PINMUX_PT35</b>
 * - <b>Features: </b> pt3.5 pin_mux
 * - <b>Param: </b>
 * | config	| Descriptions				|
 * | :----:	| :----:					|
 * | 0*		| GPIO						|
 * | 1		| Analog_port(AIN5)			|
 * | 2		| UART_TX					|
 * | 3		| DP_C						|
 */
#define	CFG_SYSCFG_PINMUX_PT35			(2)			///< {0~ 3}
//#define	CFG_SYSCFG_PINMUX_PT35			(2)			///< {0~ 3}
/**
 * @details <b>CFG_SYSCFG_PINMUX_PT36</b>
 * - <b>Features: </b> pt3.6 pin_mux
 * - <b>Param: </b>
 * | config	| Descriptions		|
 * | :----:	| :----:			|
 * | 0*		| GPIO				|
 * | 1		| Analog_port(AIN6)	|
 * | 2		| UART_RX			|
 * | 3		| DM_C				|
 */
#define	CFG_SYSCFG_PINMUX_PT36			(2)			///< {0~ 3}

/**
 * @details <b>CFG_SYSCFG_PINMUX_PT37</b>
 * - <b>Features: </b> pt3.7 pin_mux
 * - <b>Param: </b>
 * | config	| Descriptions		|
 * | :----:	| :----:			|
 * | 0*		| GPIO				|
 * | 1		| Analog_port(AIN7)	|
 * | 2		| Reserved			|
 * | 3		| Reserved			|
 */
#define	CFG_SYSCFG_PINMUX_PT37			(1)			///< {0~ 3}

/**
 * @details <b>CFG_SYSCFG_CMPVR_EN</b>
 * - <b>Features: </b> comparator 1 and comparator 0 reference voltage enable
 * - <b>Param: </b>
 * | config	| Descriptions		|
 * | :----:	| :----:			|
 * | 0*		| enable		|
 * | 1		| disable		|
 */
#define	CFG_SYSCFG_CMPVR_EN			(0)			///< 0-> disable, 1-> enable

/**
 * @details <b>CFG_SYSCFG_CMP1VRS</b>
 * - <b>Features: </b> comparator 1 reference voltage cmp1_vref selection
 * - <b>Param: </b>
 * | config	| Descriptions	|
 * | :----:	| :----:		|
 * | 0x00	| 0V2			|
 * | 0x01	| 0V4			|
 * | 0x02	| 0V66			|
 * | 0x03	| 0V8			|
 * | 0x04	| 1V23			|
 * | 0x05	| 1V58			|
 * | 0x06	| 2V18			|
 * | 0x07	| 2V6			|
 */
#define	CFG_SYSCFG_CMP1VRS			(0)			///< {0~ 7}

/**
 * @details <b>CFG_SYSCFG_CMP0VRS</b>
 * - <b>Features: </b> comparator 0 reference voltage cmp0_vref selection
 * - <b>Param: </b>
 * | config	| Descriptions	|
 * | :----:	| :----:		|
 * | 0x00	| 0V			|
 * | 0x01	| 0V32			|
 * | 0x02	| 0V6			|
 * | 0x03	| 1V0			|
 * | 0x04	| 2V0			|
 * | 0x05	| 2V7			|
 * | 0x06	| 3V0			|
 * | 0x07	| 3V3			|
 * | 0x08	| 1V2			|
 * | 0x0C	| 2V4			|
 */
#define	CFG_SYSCFG_CMP0VRS			(0)			///< {0~ 16}
/**@}*/ /*** end of name syscfg config */
/**@}*/ /*** end of group csu39fx10_sdk_chip_fwlib_syscfg_cfg */
/*******************************************************************************/




/******************************** dividing line ********************************/
/** 
 * @addtogroup syscfg_compile	attention: users do not need to care
 * @attention <b>users do not need to care</b>
 * @{
 */
/** 
 * @name syscfg_compile_reg_cfgr1
 * @{
 */
#if(CFG_SYSCFG_VTHSEL!= 0)
	#define PRE_SYSCFG_VTHSEL				1
#else	
	#define PRE_SYSCFG_VTHSEL				0
#endif	
	
#if(CFG_SYSCFG_TMP_MEAS_EN!= 0)	
	#define PRE_SYSCFG_TMP_MEAS_EN			1
#else	
	#define PRE_SYSCFG_TMP_MEAS_EN			0
#endif

#define PRE_SYSCFG_PT34FUNC_2				(CFG_SYSCFG_PINMUX_PT34/ 4)
#define PRE_SYSCFG_PT33FUNC_2				(CFG_SYSCFG_PINMUX_PT33/ 4)
/**@}*/ /*** end of name syscfg_compile_reg_cfgr1 */

/** 
 * @name syscfg_compile_reg_cfgr2
 * @{
 */
#define PRE_SYSCFG_PT10FUNC					((CFG_SYSCFG_PINMUX_PT10)& 0x03)
#define PRE_SYSCFG_PT11FUNC					((CFG_SYSCFG_PINMUX_PT11)& 0x03)
#define PRE_SYSCFG_PT12FUNC					((CFG_SYSCFG_PINMUX_PT12)& 0x03)
#define PRE_SYSCFG_PT13FUNC					((CFG_SYSCFG_PINMUX_PT13)& 0x03)
/**@}*/ /*** end of name syscfg_compile_reg_cfgr2 */

/** 
 * @name syscfg_compile_reg_cfgr3
 * @{
 */
#define PRE_SYSCFG_PT14FUNC					((CFG_SYSCFG_PINMUX_PT14)& 0x03)
#define PRE_SYSCFG_PT15FUNC					((CFG_SYSCFG_PINMUX_PT15)& 0x03)
#define PRE_SYSCFG_PT16FUNC					((CFG_SYSCFG_PINMUX_PT16)& 0x03)
#define PRE_SYSCFG_PT17FUNC					((CFG_SYSCFG_PINMUX_PT17)& 0x03)
/**@}*/ /*** end of name syscfg_compile_reg_cfgr3 */

/** 
 * @name syscfg_compile_reg_cfgr4
 * @{
 */
#define PRE_SYSCFG_PT20FUNC					((CFG_SYSCFG_PINMUX_PT20)& 0x03)
#define PRE_SYSCFG_PT21FUNC					((CFG_SYSCFG_PINMUX_PT21)& 0x03)
#define PRE_SYSCFG_PT22FUNC					((CFG_SYSCFG_PINMUX_PT22)& 0x03)
#define PRE_SYSCFG_PT23FUNC					((CFG_SYSCFG_PINMUX_PT23)& 0x03)
/**@}*/ /*** end of name syscfg_compile_reg_cfgr4 */

/** 
 * @name syscfg_compile_reg_cfgr5
 * @{
 */
#define PRE_SYSCFG_PT24FUNC					((CFG_SYSCFG_PINMUX_PT24)& 0x03)
#define PRE_SYSCFG_PT25FUNC					((CFG_SYSCFG_PINMUX_PT25)& 0x03)///// 3--ICD 功能
#define PRE_SYSCFG_PT25FUNC_NOSWD			((0)& 0x03)/////0-IO 1-Analog_port(AIN13) 2- PWM3H	 3--ICD 功能
#define PRE_SYSCFG_PT26FUNC					((CFG_SYSCFG_PINMUX_PT26)& 0x03)
/**@}*/ /*** end of name syscfg_compile_reg_cfgr5 */

/** 
 * @name syscfg_compile_reg_cfgr6
 * @{
 */
#define PRE_SYSCFG_PT30FUNC					((CFG_SYSCFG_PINMUX_PT30)& 0x03)
#define PRE_SYSCFG_PT31FUNC					((CFG_SYSCFG_PINMUX_PT31)& 0x03)
#define PRE_SYSCFG_PT32FUNC					((CFG_SYSCFG_PINMUX_PT32)& 0x03)
#define PRE_SYSCFG_PT33FUNC					((CFG_SYSCFG_PINMUX_PT33)& 0x03)
/**@}*/ /*** end of name syscfg_compile_reg_cfgr6 */

/** 
 * @name syscfg_compile_reg_cfgr7
 * @{
 */
#define PRE_SYSCFG_PT34FUNC					((CFG_SYSCFG_PINMUX_PT34)& 0x03)
#define PRE_SYSCFG_PT35FUNC					((CFG_SYSCFG_PINMUX_PT35)& 0x03)
#define PRE_SYSCFG_PT36FUNC					((CFG_SYSCFG_PINMUX_PT36)& 0x03)
#define PRE_SYSCFG_PT37FUNC					((CFG_SYSCFG_PINMUX_PT37)& 0x03)
/**@}*/ /*** end of name syscfg_compile_reg_cfgr7 */

/** 
 * @name syscfg_compile_reg_cfgr8
 * @{
 */
#if(CFG_SYSCFG_CMPVR_EN!= 0)
	#define PRE_SYSCFG_CMPVR_EN				1
#else	
	#define PRE_SYSCFG_CMPVR_EN				0
#endif

#define PRE_SYSCFG_CMP1VRS					CFG_SYSCFG_CMP1VRS
#define PRE_SYSCFG_CMP0VRS					CFG_SYSCFG_CMP0VRS
/**@}*/ /*** end of name syscfg_compile_reg_cfgr8 */


/** 
 * @name syscfg_compile_warning
 * @attention <b>compile warning message</b>
 * @{
 */
#if(0)
	#warning "Warning: CFG_SYSCFG_XXX define error, will be redefined!"
#endif
/**@}*/ /*** end of name syscfg_compile_warning */
/**@}*/ /*** end of group syscfg_compile */
/*******************************************************************************/




/******************************** dividing line ********************************/
/**
 * @addtogroup syscfg_reg_default	reg_default_value
 * @{
 */
/** 
 * @name syscfg_reg
 * @par 示例
 * @code
 *		void test( void )
 *		{
 *			CFGR1= PRE_CFGR1_DEFAULT;
 *			CFGR2= PRE_CFGR2_DEFAULT;
 *			CFGR3= PRE_CFGR3_DEFAULT;
 *			CFGR4= PRE_CFGR4_DEFAULT;
 *			CFGR5= PRE_CFGR5_DEFAULT;
 *			CFGR6= PRE_CFGR6_DEFAULT;
 *			CFGR7= PRE_CFGR7_DEFAULT;
 *			CFGR8= PRE_CFGR8_DEFAULT;
 *		}
 * @endcode
 * @{
 */                                              /////PRE_SYSCFG_VTHSEL
#define PRE_CFGR1_DEFAULT					(((1<< SYSCFG_VTHSEL_POS)& SYSCFG_VTHSEL_MASK)|						\
												((PRE_SYSCFG_TMP_MEAS_EN<< SYSCFG_TMP_MEAS_EN_POS)& SYSCFG_TMP_MEAS_EN_MASK)|	\
												((PRE_SYSCFG_PT34FUNC_2<< SYSCFG_PT34FUNC_2_POS)& SYSCFG_PT34FUNC_2_MASK)|		\
												((PRE_SYSCFG_PT33FUNC_2<< SYSCFG_PT33FUNC_2_POS)& SYSCFG_PT33FUNC_2_MASK))
#define PRE_CFGR2_DEFAULT					(((PRE_SYSCFG_PT10FUNC<< SYSCFG_PT10FUNC_POS)& SYSCFG_PT10FUNC_MASK)|		\
												((PRE_SYSCFG_PT11FUNC<< SYSCFG_PT11FUNC_POS)& SYSCFG_PT11FUNC_MASK)|	\
												((PRE_SYSCFG_PT12FUNC<< SYSCFG_PT12FUNC_POS)& SYSCFG_PT12FUNC_MASK)|	\
												((PRE_SYSCFG_PT13FUNC<< SYSCFG_PT13FUNC_POS)& SYSCFG_PT13FUNC_MASK))
#define PRE_CFGR3_DEFAULT					(((PRE_SYSCFG_PT14FUNC<< SYSCFG_PT14FUNC_POS)& SYSCFG_PT14FUNC_MASK)|		\
												((PRE_SYSCFG_PT15FUNC<< SYSCFG_PT15FUNC_POS)& SYSCFG_PT15FUNC_MASK)|	\
												((PRE_SYSCFG_PT16FUNC<< SYSCFG_PT16FUNC_POS)& SYSCFG_PT16FUNC_MASK)|	\
												((PRE_SYSCFG_PT17FUNC<< SYSCFG_PT17FUNC_POS)& SYSCFG_PT17FUNC_MASK))
#define PRE_CFGR4_DEFAULT					(((PRE_SYSCFG_PT20FUNC<< SYSCFG_PT20FUNC_POS)& SYSCFG_PT20FUNC_MASK)|		\
												((PRE_SYSCFG_PT21FUNC<< SYSCFG_PT21FUNC_POS)& SYSCFG_PT21FUNC_MASK)|	\
												((PRE_SYSCFG_PT22FUNC<< SYSCFG_PT22FUNC_POS)& SYSCFG_PT22FUNC_MASK)|	\
												((PRE_SYSCFG_PT23FUNC<< SYSCFG_PT23FUNC_POS)& SYSCFG_PT23FUNC_MASK))
#define PRE_CFGR5_DEFAULT					(((PRE_SYSCFG_PT24FUNC<< SYSCFG_PT24FUNC_POS)& SYSCFG_PT24FUNC_MASK)|		\
												((PRE_SYSCFG_PT25FUNC<< SYSCFG_PT25FUNC_POS)& SYSCFG_PT25FUNC_MASK)|	\
												((PRE_SYSCFG_PT26FUNC<< SYSCFG_PT26FUNC_POS)& SYSCFG_PT26FUNC_MASK))
#define PRE_CFGR5_DEFAULT_NO_SWD			(((PRE_SYSCFG_PT24FUNC<< SYSCFG_PT24FUNC_POS)& SYSCFG_PT24FUNC_MASK)|		\
												((PRE_SYSCFG_PT25FUNC_NOSWD<< SYSCFG_PT25FUNC_POS)& SYSCFG_PT25FUNC_MASK)|	\
												((PRE_SYSCFG_PT26FUNC<< SYSCFG_PT26FUNC_POS)& SYSCFG_PT26FUNC_MASK))								
												
#define PRE_CFGR6_DEFAULT					(((PRE_SYSCFG_PT30FUNC<< SYSCFG_PT30FUNC_POS)& SYSCFG_PT30FUNC_MASK)|		\
												((PRE_SYSCFG_PT31FUNC<< SYSCFG_PT31FUNC_POS)& SYSCFG_PT31FUNC_MASK)|	\
												((PRE_SYSCFG_PT32FUNC<< SYSCFG_PT32FUNC_POS)& SYSCFG_PT32FUNC_MASK)|	\
												((PRE_SYSCFG_PT33FUNC<< SYSCFG_PT33FUNC_POS)& SYSCFG_PT33FUNC_MASK))
 #define PRE_CFGR6_NTC_IO					(((	((0)& 0x03)<< SYSCFG_PT30FUNC_POS)& SYSCFG_PT30FUNC_MASK)|		\
												((PRE_SYSCFG_PT31FUNC<< SYSCFG_PT31FUNC_POS)& SYSCFG_PT31FUNC_MASK)|	\
												((PRE_SYSCFG_PT32FUNC<< SYSCFG_PT32FUNC_POS)& SYSCFG_PT32FUNC_MASK)|	\
												((PRE_SYSCFG_PT33FUNC<< SYSCFG_PT33FUNC_POS)& SYSCFG_PT33FUNC_MASK))
												
#define PRE_CFGR7_DEFAULT					(((PRE_SYSCFG_PT34FUNC<< SYSCFG_PT34FUNC_POS)& SYSCFG_PT34FUNC_MASK)|		\
												((PRE_SYSCFG_PT35FUNC<< SYSCFG_PT35FUNC_POS)& SYSCFG_PT35FUNC_MASK)|	\
												((PRE_SYSCFG_PT36FUNC<< SYSCFG_PT36FUNC_POS)& SYSCFG_PT36FUNC_MASK)|	\
												((PRE_SYSCFG_PT37FUNC<< SYSCFG_PT37FUNC_POS)& SYSCFG_PT37FUNC_MASK))
#define PRE_CFGR8_DEFAULT					(((PRE_SYSCFG_CMPVR_EN<< SYSCFG_CMPVR_EN_POS)& SYSCFG_CMPVR_EN_MASK)|		\
												((PRE_SYSCFG_CMP1VRS<< SYSCFG_CMP1VRS_POS)& SYSCFG_CMP1VRS_MASK)|	\
												((PRE_SYSCFG_CMP0VRS<< SYSCFG_CMP0VRS_POS)& SYSCFG_CMP0VRS_MASK))
/**@}*/ /*** end of name syscfg_reg */
/**@}*/ /*** end of group syscfg_reg_default */
/*******************************************************************************/




/******************************** dividing line ********************************/
/** 
 * @addtogroup syscfg_api	api
 * @{
 */
/** 
 * @name syscfg_api
 * @{
 */
/**
 * @brief 	<b>Description:</b> syscfg initialization.
 * @details <b>Function prototype:</b> void syscfg_init(void);
 * @param[in]  null	.
 * @param[out] null.
 * 
 * @return  null
 * @par Example
 * @code
 *		void test( void )
 *		{
 * 			syscfg_init();
 *		}
 * @endcode
 */
void syscfg_init(void);

/**@}*/ /*** end of name syscfg_api */
/**@}*/ /*** end of group syscfg_api */
/**@}*/ /*** end of group csu39fx10_sdk_chip_fwlib_syscfg */
/**@}*/ /*** end of group csu39fx10_sdk_chip_fwlib */
/**@}*/ /*** end of group csu39fx10_sdk_chip */
/*******************************************************************************/




#ifdef __cplusplus
}
#endif

#endif  //__CSU39FX10_SYSCFG_H__


/*** (C) COPYRIGHT 2020 Chipsea Technologies (Shenzhen) Corp. ***/
